---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: focal
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    privileged: true
    pre_build_image: true
    docker_networks:
      - name: molecule_rabbitmq
        ipam_config:
          - subnet: "10.30.50.0/24"
    etc_hosts: >
      {
        "bionic" : "10.30.50.12",
      }
    networks:
      - name: molecule_rabbitmq
        ipv4_address: "10.30.50.11"

  - name: bionic
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    privileged: true
    pre_build_image: true
    etc_hosts: >
      {
        "focal" : "10.30.50.11",
      }
    networks:
      - name: molecule_rabbitmq
        ipv4_address: "10.30.50.12"

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        install_python3: true
        rabbitmq_ha: true
        rabbitmq_user:
          username: user
          password: pass
        _verify_expected_master: focal
    host_vars:
      focal:
        rabbitmq_role: master
      bionic:
        rabbitmq_role: slave
verifier:
  name: ansible
